stages:
  - before_build
  - deploy

include:
  - project: "sanger-pathogens/templates/ci-templates"
    ref: "PAT-2100/CI_templates_for_pipeline_deployment_on_farm"
    file: "before-build-template.yml"
  - project: "sanger-pathogens/templates/ci-templates"
    ref: "PAT-2100/CI_templates_for_pipeline_deployment_on_farm"
    file: "farm22/farm-deploy.yml"

eslint:
  rules:
    - when: never

talisman:
  variables:
    TALISMAN_OPTS: "--scan --ignoreHistory"

deploy_to_farm:
  variables:
    FARM_NAME: "strain-mapper"
    # TODO the install path below is a temporary test deployment directory
    FARM_PATH: "/tmp/data/pam/applications/farm-etc-testing/PAT-2100_testing_installs"
    FARM_FILE_CHMOD: "[strain-mapper.sh]='+x' [main.nf]='+x'"
    FARM_FILE_RENAME: "[strain-mapper.sh]='strain-mapper'"
    # TODO the module path below is a temporary test directory
    FARM_MODULE_PATH: "/tmp/data/pam/applications/farm-etc-testing/PAT-2100_testing_installs/modules/"
