stages:
  - before_build
  - deploy
  - security_scans
  - after_security_scans

include:
  - project: "sanger-pathogens/templates/ci-templates"
    ref: "$CI_CD_TEMPLATES_LATEST_STABLE"
    file: "before-build-template.yml"
  - project: "sanger-pathogens/templates/ci-templates"
    ref: "$CI_CD_TEMPLATES_LATEST_STABLE"
    file: "farm22/pipeline-deploy.yml"
  - project: "sanger-pathogens/templates/ci-templates"
    ref: "$CI_CD_TEMPLATES_LATEST_STABLE"
    file: "security-scans-standard-template.yml"

eslint:
  rules:
    - when: never

talisman:
  variables:
    TALISMAN_OPTS: "--scan --ignoreHistory"

pipeline_deploy_to_farm_prod:
  variables:
    TAG_PATTERN: /^v[0-9]+\.[0-9]+\.[0-9]+/

.pipeline_deploy_to_farm:
  variables:
    FARM_NAME: "strain-mapper"
    FARM_FILE_CHMOD: "[strain-mapper.sh]='+x' [main.nf]='+x'"
    FARM_FILE_SED: "[main.nf]='s/nextflow +run +(.|main.nf)/${FARM_NAME}/' [nextflow.config]='s/\\{\\{strain_mapper_version\\}\\}/${CI_COMMIT_REF_NAME}/'"
    FARM_FILE_RENAME: "[strain-mapper.sh]='strain-mapper'"

# there's no docker build in this repo so disable container scan
container_scanning:
  rules:
    - when: never
