#!/usr/bin/env nextflow

/*
========================================================================================
    HELP
========================================================================================
*/

def printHelp() {
    log.info """
    Usage:
    nextflow run main.nf [--manifest_of_reads <path to manifest>] [--manifest_of_lanes <path to manifest>] [--studyid <study_id>, [--runid <run_id>, [--laneid <lane_id>, [--plexid <plex_id>]]]] [--method <calling method>] --reference <path to reference> --outdir <path to results folder>

    Input parameters:

      Sequencing reads:
        There are two ways of providing input reads, which can be combined:

        1) through direct input of compressed fastq sequence reads files. This kind of input is passed by specifying the paths to the
           read files via a manifest listing the pair of read files pertaing to a sample, one per row.

        --manifest_of_reads          Manifest containing per-sample paths to .fastq.gz files (optional)

        2) through specification of data to be downloaded from iRODS. Each sample is defined by a combination of study, run, lane and plex ids
           (these ids correspond to the reference of the sequencing experiment). Run, lane and plex ids are not mandatory: when provided, these 
           parameters gradually restrict of files to be downloaded; when ommitted, samples for all possible values are retrieved.
           This information can be provided via a combination of workflow parameters passed on through command line options: --studyid, --runid, 
           --laneid and --plexid; this defines a single sequencing dataset based on a combination of study, run, lane and plex ids.

        --studyid                    ID of sequencing study including read data to use as pipeline input (optional)
        --runid                      ID of sequencing run including read data to use as pipeline input (optional)
        --laneid                     ID of sequencing lane (as in a lane within of a flow cell) including read data to use as pipeline input (optional)
        --plexid                     ID of sequencing lane multiplex tag index including read data to use as pipeline input (optional)

            Alternatively, the user can provide a manifest listing a batch of such combinations.

       --manifest_of_lanes          Manifest containing specification of data to be downloaded from iRODS (optional)
                                     Each row defines a sequencing dataset based on a combination of study, run, lane and plex ids.
                                     Run, lane and plex ids are not mandatory (field in csv file can be left blank); 
                                     when provided, these gradually restrict of files to be downloaded.

      NB: the real lane id is different from the the so-called \"lane\" id, a term commonly used in Sanger referring to this sequencing run output unit, usually labelled with this syntax: 48106_1#83.
      In this, the run id is 48106, the (real) lane id is 1 and the plex id is 83.
        
      Other input parameters:
        --reference                  Reference to map reads against (mandatory)
        --method                     Variant calling strategy to use. Valid options: bcftools, gatk. [default: bcftools] (optional)
    
    Output parameters:
        --outdir                     Specify output directory [default: ./results] (optional)

    General options:
        --help                       Print summary of main parameters and options (optional)
        --help_all                   Print extensive list of parameters and options (optional)
    """.stripIndent()
}

def printHelpAll() {
    printHelp()
    log.info """

    Procesing options:
      iRODS extractor options:
        --cleanup_intermediate_files_irods_extractor  [default = false]

      Strain-mapper read mapping options:
        --report_ref_and_alt         Include both REF and ALT variants in the VCF output. [default = false] (optional)
        --bcftools_vcf_filter        Filter variants in VCF file generated by bcftools. See https://samtools.github.io/bcftools/bcftools.html#expressions
                                      for valid syntax. By default, remove records with a quality score below 50, fewer than 8 reads (read depth), or
                                      fewer than 4 supporting reads per strand (allelic depth).
                                      [default = "QUAL>=50 & MIN(DP)>=8 & ((ALT!="." & DP4[2]>3 & DP4[3]>3) | (ALT="." & DP4[0]>3 & DP4[1]>3))"] (optional)
        --gatk_vcf_filter            Filter variants in VCF file generated by bcftools. See https://samtools.github.io/bcftools/bcftools.html#expressions
                                      for valid syntax. By default, remove records with a quality score below 50, with fewer than 8 reads (read depth), or
                                      fewer than 8 supporting reads per allele (allelic depth).
                                      [default = "QUAL>=50 & MIN(FORMAT/DP)>=8 & ((ALT!="." & FORMAT/AD[*:1]>7) | (ALT="." & FORMAT/AD[*:0]>7))"] (optional)
        --skip_filtering             Do not filter variants using filter parameters --bcftools_vcf_filter or --gatk_vcf_filter. [default = false] (optional)
        --keep_raw_vcf               Save the unfiltered VCF file, i.e. direct output of `bcftools call` or `gatk haplotypecaller`. This can be combined with
                                      --report_ref_and_alt to report all (unfiltered, REF and ALT) variants;
                                      only relevant when --skip_filtering=false. [default = false]
        --keep_sorted_bam            Save the mapping file (sorted BAM). [default = false]
        --keep_gatk_bam              Save a BAM file of realigned reads provided by GATK haptlotypecaller. [default = false]
    """.stripIndent()
}

if (params.help) {
    printHelp()
    exit(0)
}
if (params.help_all) {
    printHelpAll()
    exit(0)
}

/*
========================================================================================
    VALIDATE INPUTS
========================================================================================
*/

def validate_path_param(
    param_option, 
    param, 
    type="file", 
    mandatory=true) {
        valid_types=["file", "directory"]
        if (!valid_types.any { it == type }) {
                log.error("Invalid type '${type}'. Possibilities are ${valid_types}.")
                return 1
        }
        param_name = (param_option - "--").replaceAll("_", " ")
        if (param) {
            def file_param = file(param)
            if (!file_param.exists()) {
                log.error("The given ${param_name} '${param}' does not exist.")
                return 1
            } else if (
                (type == "file" && !file_param.isFile())
                ||
                (type == "directory" && !file_param.isDirectory())
            ) {
                log.error("The given ${param_name} '${param}' is not a ${type}.")
                return 1
            }
        } else if (mandatory) {
            log.error("No ${param_name} specified. Please specify one using the ${param_option} option.")
            return 1
        }
        return 0
    }

def validate_choice_param(param_option, param, choices) {
    param_name = (param_option - "--").replaceAll("_", " ")
    if (param) {
        if (!choices.any { it.contains(param.toString()) }) {
            log.error("Please specify the ${param_name} using the ${param_option} option. Possibilities are ${choices}.")
            return 1
        }
    } else {
        log.error("Please specify the ${param_name} using the ${param_option} option")
        return 1
    }
    return 0
}

def validate_parameters() {
    def errors = 0

    errors += validate_path_param("--reference", params.reference)
    errors += validate_choice_param("--method", params.method, ["bcftools", "gatk"])

    if ((params.manifest_of_reads == "") || (params.manifest_of_lanes == "") || (params.studyid == -1)){
        log.error(String.format("No input provided; please specify at least one of the following options: --manifest_of_reads, --manifest_of_lanes or --studyid", errors))
        errors += 1
    }

    if (errors > 0) {
        log.error(String.format("%d errors detected", errors))
        exit 1
    }
}

//validate_parameters()

/*
========================================================================================
    IMPORT MODULES/SUBWORKFLOWS
========================================================================================
*/

//
// SUBWORKFLOWS
//
include { INPUT_CHECK } from './subworkflows/input_check'
include { STRAIN_MAPPER } from './assorted-sub-workflows/strain_mapper/strain_mapper.nf'
include { IRODS_EXTRACTOR } from './assorted-sub-workflows/irods_extractor/subworkflows/irods.nf'
include { IRODS_MANIFEST_PARSE } from './assorted-sub-workflows/irods_extractor/subworkflows/irods_manifest_parse.nf'


/*
========================================================================================
    RUN MAIN WORKFLOW
========================================================================================
*/

workflow {

    //
    // REFERENCE PROCESSING 
    //
    reference = file(params.reference, checkIfExists: true)

    //
    // SUBWORKFLOW: Read in samplesheet, validate and stage input files
    //
    if (params.manifest_of_reads) {
        input_reads_ch = file(params.manifest_of_reads)
        INPUT_CHECK (
            input_reads_ch
        )
        INPUT_CHECK.out.shortreads
            .dump(tag: 'ch_reads_from_manifest')
            .set { ch_reads_from_manifest }
    } else {
        Channel.of("none").set{ ch_reads_from_manifest }
    }
    //
    // SUBWORKFLOW: Read in study, run, etc. parameters and pull data from iRODS
    //

    // take iRODS dataset specification from CLI options
    if (params.studyid > 0) {
        param_input = Channel.of(["${params.studyid}", "${params.runid}", "${params.laneid}", "${params.plexid}"])
        
        param_input.map{ studyid, runid, laneid, plexid ->
            meta = [:]
            if (studyid > 0) {meta.studyid = studyid}
            if (runid > 0) {meta.runid = runid}
            if (laneid > 0 ) {meta.laneid = laneid}
            if (plexid > 0 ) {meta.plexid = plexid}
            meta
        }.set{ input_irods_from_opt_ch } 
    } else {
        Channel.of("none").set{ input_irods_from_opt_ch }
    }    
    // take iRODS dataset specification from manifest of lanes
    if (params.manifest_of_lanes) {
        IRODS_MANIFEST_PARSE(params.manifest_of_lanes)
        | set{ input_irods_from_man_ch }
    } else {
        Channel.of("none").set{ input_irods_from_man_ch}
    }

    // combine iRODS specs input channels
    input_irods_from_opt_ch.mix(input_irods_from_man_ch).set{ input_irods_ch }

    // pull reads from iRODS
    IRODS_EXTRACTOR(
        input_irods_ch.filter{ it != "none"}
    )

    // change channel structure to match that from INPUT_CHECK
    IRODS_EXTRACTOR.out.reads_ch.map{ meta, read_1, read_2 ->
        meta_new = [:]
        meta_new.id = meta.ID
        reads = [read_1, read_2]
        [ meta_new, reads ]
    }.set{ irods_ready_to_map_ch }

    // combine reads input channels
    irods_ready_to_map_ch.mix(ch_reads_from_manifest.filter{ it != "none"}).set{ all_reads_ready_to_map_ch }

    //
    // SUBWORKFLOW: actual processing; 
    // please refer to  the Nextflow subworkflow strain_mapper
    // in the submodule repository assorted-sub-workflows
    //

    STRAIN_MAPPER( all_reads_ready_to_map_ch, reference )

}
/*
========================================================================================
    THE END
========================================================================================
*/
